# Generated by Django 2.2 on 2020-01-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animalType', models.CharField(max_length=15)),
                ('animalAge', models.SmallIntegerField()),
                ('animalName', models.CharField(max_length=50)),
                ('animalArrivalDate', models.DateField()),
                ('animalGender', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketValid', models.DateField()),
                ('ticketAge', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitorAge', models.SmallIntegerField()),
                ('visitorName', models.CharField(max_length=50)),
                ('visitorGender', models.CharField(max_length=6)),
            ],
        ),
    ]
