# Generated by Django 2.2 on 2020-01-10 11:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticketAge',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticketAgeCheck',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticketBought',
            field=models.DateField(default=datetime.datetime(2020, 1, 10, 11, 11, 2, 175692, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animalArrivalDate',
            field=models.DateField(default=datetime.datetime(2020, 1, 10, 11, 11, 2, 174694, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animalGender',
            field=models.IntegerField(choices=[(1, 'Mail'), (2, 'Femail'), (3, 'Other')], default=3),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animalName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animalType',
            field=models.IntegerField(choices=[(1, 'Badger - Барсук'), (2, 'Monkey - Обезьяна'), (3, 'Bear - Медведь')], default=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticketValid',
            field=models.DateField(default=datetime.datetime(2020, 1, 11, 11, 11, 2, 175692, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitorGender',
            field=models.IntegerField(choices=[(1, 'Mail'), (2, 'Femail'), (3, 'Other')], default=3),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitorName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
