# Generated by Django 2.2 on 2020-01-10 11:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200110_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticketVisitor',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.Visitor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='animalArrivalDate',
            field=models.DateField(default=datetime.datetime(2020, 1, 10, 11, 21, 6, 189565, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticketBought',
            field=models.DateField(default=datetime.datetime(2020, 1, 10, 11, 21, 6, 190529, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticketValid',
            field=models.DateField(default=datetime.datetime(2020, 1, 11, 11, 21, 6, 190529, tzinfo=utc)),
        ),
    ]
