# Generated by Django 2.2 on 2020-01-10 12:47

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200110_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animalAge',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animalArrivalDate',
            field=models.DateField(default=datetime.datetime(2020, 1, 10, 12, 47, 37, 174143, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticketBought',
            field=models.DateField(default=datetime.datetime(2020, 1, 10, 12, 47, 37, 175146, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticketValid',
            field=models.DateField(default=datetime.datetime(2020, 1, 11, 12, 47, 37, 175146, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitorAge',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)]),
        ),
    ]
