# Generated by Django 2.2 on 2020-01-10 15:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20200110_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animalArrivalDate',
            field=models.DateField(default=datetime.datetime(2020, 1, 10, 15, 43, 16, 827196, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animalGender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], default=3),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticketBought',
            field=models.DateField(default=datetime.datetime(2020, 1, 10, 15, 43, 16, 827196, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticketValid',
            field=models.DateField(default=datetime.datetime(2020, 1, 11, 15, 43, 16, 827196, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='visit',
            name='timeOfVisit',
            field=models.DateField(default=datetime.datetime(2020, 1, 10, 15, 43, 16, 827196, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitorGender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], default=3),
        ),
    ]
