# Generated by Django 2.2 on 2020-01-10 17:35

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20200110_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticketValid',
        ),
        migrations.AlterField(
            model_name='animal',
            name='animalArrivalDate',
            field=models.DateField(default=datetime.datetime(2020, 1, 10, 17, 35, 38, 528884, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticketBought',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='visit',
            name='timeOfVisit',
            field=models.DateField(default=datetime.datetime(2020, 1, 10, 17, 35, 38, 529886, tzinfo=utc)),
        ),
    ]
