# Generated by Django 2.2 on 2020-01-10 17:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20200110_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticketAgeCheck',
        ),
        migrations.AlterField(
            model_name='animal',
            name='animalArrivalDate',
            field=models.DateField(default=datetime.datetime(2020, 1, 10, 17, 41, 13, 453715, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='visit',
            name='timeOfVisit',
            field=models.DateField(default=datetime.datetime(2020, 1, 10, 17, 41, 13, 453715, tzinfo=utc)),
        ),
    ]
