# Generated by Django 2.2 on 2020-01-29 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(1990, 1, 29, 8, 59, 28, 194353), verbose_name='Дата рождения'),
        ),
    ]
