# Generated by Django 2.2 on 2020-01-29 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200130_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(1990, 1, 29, 12, 13, 58, 99504), verbose_name='Дата рождения'),
        ),
    ]
