# Generated by Django 2.2 on 2020-01-29 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200130_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(1990, 1, 29, 12, 22, 37, 870127), verbose_name='Дата рождения'),
        ),
    ]
