# Generated by Django 2.2 on 2020-01-30 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200130_0022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tovar',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='myuser',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(1990, 1, 29, 23, 53, 31, 220601), verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
